name: lingua_ml
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_ml_kit: ^0.7.3
  image_picker: ^0.8.4+4
  shared_preferences: ^2.0.11
  camera: ^0.9.4+5
  fluttertoast: ^8.0.8
  page_transition: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: DEFAULT
      fonts:
        - asset: assets/fonts/Noto_Serif/NotoSerif-Regular.ttf
    - family: JAPANESE
      fonts:
        - asset: assets/fonts/Noto_Serif_JP/NotoSerifJP-Regular.otf
    - family: DEVANAGARI
      fonts:
        - asset: assets/fonts/Noto_Serif_Devanagari/static/NotoSerifDevanagari/NotoSerifDevanagari-Regular.ttf
    - family: CHINESE
      fonts:
        - asset: assets/fonts/Noto_Serif_TC/NotoSerifTC-Regular.otf
    - family: KOREAN
      fonts:
        - asset: assets/fonts/Noto_Serif_KR/NotoSerifKR-Regular.otf
